language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
script: grunt
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- grunt gh-pages
env:
- secure: QOeaxZfElh31USvqQxCtAe1tBl8d9EVLLQgNwz0F5NKj8bkhg3h7LRW+xNR2MorJZNC8Fydhtcjy3WBNuBWx0JeJR/iDplScEQ95PZFeISi+BuZj5IHmpPklkGEbobVqovyR8uW1qMN4resh3FLAxNPkQKgp90KoHJ3Mx9kfN4M=
